[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
bitvec = "1.0.0-rc1"
itertools = "0.10.1"
num = "0.4.0"
thiserror = "1.0.30"

[dev-dependencies]
criterion = "0.3.3"
indoc = "1.0.3"

[[bench]]
name = "solution_benchmark"
harness = false
